version: "3.3"
services:
  app:
    command: mvn clean install -DskipTests
    # container_name: app-springboot-postgresql
    image: url-shortner-docker
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql
      - redis
  dbpostgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db
  redis:
    image: redis
    ports: "6379:6379"